name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Install minicover
      run: dotnet tool install --global minicover --version 3.0.6
    
    - name: Restore dependencies
      run: dotnet restore **/CQRS.Mediatr.Lite.sln
    
    - name: Build
      run: dotnet build **/CQRS.Mediatr.Lite.sln --no-restore
    
    - name: Instrument
      run: minicover instrument
    
    - name: Test
      run: dotnet test **/CQRS.Mediatr.Lite.sln --no-build --verbosity normal
    
    - name: Uninstrument
      run: minicover uninstrument
    
    - name: Report
      run: minicover report --threshold 95
      if: ${{ github.event_name == 'pull_request' }}
    
    - name: Report coveralls
      run: minicover coverallsreport --repo-token ${{ secrets.COVERALLS_TOKEN }} --branch ${{ env.BRANCH_NAME }}
      if: ${{ github.event_name == 'push' }}
